// ── State node positions as fractions of the background image (india_bg.png) ─
// fx = left→right (0..1), fy = top→bottom (0..1)
// Calibrated to match where state names appear in the generated map image
const STATE_DATA = {
    "Jammu & Kashmir": { fx: 0.35, fy: 0.11 },
    "Himachal Pradesh": { fx: 0.38, fy: 0.20 },
    "Punjab": { fx: 0.27, fy: 0.25 },
    "Haryana": { fx: 0.31, fy: 0.31 },
    "Delhi": { fx: 0.37, fy: 0.33 },
    "Uttarakhand": { fx: 0.47, fy: 0.25 },
    "Rajasthan": { fx: 0.22, fy: 0.41 },
    "Uttar Pradesh": { fx: 0.50, fy: 0.38 },
    "Bihar": { fx: 0.62, fy: 0.40 },
    "Jharkhand": { fx: 0.58, fy: 0.49 },
    "West Bengal": { fx: 0.67, fy: 0.47 },
    "Sikkim": { fx: 0.63, fy: 0.33 },
    "Assam": { fx: 0.76, fy: 0.40 },
    "Meghalaya": { fx: 0.72, fy: 0.46 },
    "Arunachal Pradesh": { fx: 0.86, fy: 0.28 },
    "Nagaland": { fx: 0.86, fy: 0.42 },
    "Manipur": { fx: 0.84, fy: 0.49 },
    "Mizoram": { fx: 0.81, fy: 0.54 },
    "Tripura": { fx: 0.74, fy: 0.53 },
    "Gujarat": { fx: 0.13, fy: 0.48 },
    "Maharashtra": { fx: 0.27, fy: 0.60 },
    "Madhya Pradesh": { fx: 0.40, fy: 0.50 },
    "Chhattisgarh": { fx: 0.53, fy: 0.54 },
    "Odisha": { fx: 0.62, fy: 0.56 },
    "Telangana": { fx: 0.42, fy: 0.64 },
    "Andhra Pradesh": { fx: 0.44, fy: 0.74 },
    "Karnataka": { fx: 0.30, fy: 0.76 },
    "Goa": { fx: 0.22, fy: 0.70 },
    "Kerala": { fx: 0.26, fy: 0.87 },
    "Tamil Nadu": { fx: 0.38, fy: 0.85 },
};

// ── Adjacency edges (states sharing a border) ─────────────────────────────────
const STATE_EDGES = [
    ["Jammu & Kashmir", "Himachal Pradesh"],
    ["Jammu & Kashmir", "Punjab"],
    ["Himachal Pradesh", "Punjab"],
    ["Himachal Pradesh", "Haryana"],
    ["Himachal Pradesh", "Uttarakhand"],
    ["Himachal Pradesh", "Uttar Pradesh"],
    ["Punjab", "Haryana"],
    ["Punjab", "Rajasthan"],
    ["Haryana", "Delhi"],
    ["Haryana", "Uttar Pradesh"],
    ["Haryana", "Rajasthan"],
    ["Delhi", "Uttar Pradesh"],
    ["Uttarakhand", "Uttar Pradesh"],
    ["Rajasthan", "Uttar Pradesh"],
    ["Rajasthan", "Madhya Pradesh"],
    ["Rajasthan", "Gujarat"],
    ["Uttar Pradesh", "Madhya Pradesh"],
    ["Uttar Pradesh", "Chhattisgarh"],
    ["Uttar Pradesh", "Bihar"],
    ["Uttar Pradesh", "Jharkhand"],
    ["Bihar", "Jharkhand"],
    ["Bihar", "West Bengal"],
    ["Jharkhand", "West Bengal"],
    ["Jharkhand", "Odisha"],
    ["Jharkhand", "Chhattisgarh"],
    ["West Bengal", "Sikkim"],
    ["West Bengal", "Assam"],
    ["West Bengal", "Odisha"],
    ["Sikkim", "Assam"],
    ["Assam", "Arunachal Pradesh"],
    ["Assam", "Nagaland"],
    ["Assam", "Manipur"],
    ["Assam", "Mizoram"],
    ["Assam", "Tripura"],
    ["Assam", "Meghalaya"],
    ["Arunachal Pradesh", "Nagaland"],
    ["Nagaland", "Manipur"],
    ["Manipur", "Mizoram"],
    ["Mizoram", "Tripura"],
    ["Gujarat", "Madhya Pradesh"],
    ["Gujarat", "Maharashtra"],
    ["Maharashtra", "Madhya Pradesh"],
    ["Maharashtra", "Chhattisgarh"],
    ["Maharashtra", "Telangana"],
    ["Maharashtra", "Karnataka"],
    ["Maharashtra", "Goa"],
    ["Madhya Pradesh", "Chhattisgarh"],
    ["Chhattisgarh", "Odisha"],
    ["Chhattisgarh", "Andhra Pradesh"],
    ["Chhattisgarh", "Telangana"],
    ["Odisha", "Andhra Pradesh"],
    ["Telangana", "Andhra Pradesh"],
    ["Telangana", "Karnataka"],
    ["Andhra Pradesh", "Karnataka"],
    ["Andhra Pradesh", "Tamil Nadu"],
    ["Karnataka", "Goa"],
    ["Karnataka", "Kerala"],
    ["Karnataka", "Tamil Nadu"],
    ["Kerala", "Tamil Nadu"],
];
